-- Owner-authorized retirement of Polymarket, 2026-09-28.
-- Irreversible data removal. BTC/auth and all applied migration checksums stay intact.
-- Explicit inventory; no CASCADE, no global HOLD/trigger bypass or volume deletion.
-- The migration runner wraps this whole file in one transaction.
SET LOCAL lock_timeout = '2s';
SET LOCAL statement_timeout = '120s';

-- Refuse unknown evidence references; the production inventory had no legacy pins.
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM retention_evidence_pins WHERE table_name = ANY(ARRAY[
        'fast_config_versions',
        'fast_wallet_state',
        'fundamental_calibration_reports',
        'fundamental_estimates',
        'fundamental_gate_reports',
        'fundamental_labels',
        'fundamental_model_events',
        'fundamental_models',
        'graph_edges',
        'graph_sanity_vetoes',
        'graph_violations',
        'paper_feature_windows',
        'paper_fill_reports',
        'paper_fill_samples',
        'paper_financial_owners',
        'paper_kill_switch',
        'paper_ledger_events',
        'paper_ledger_owners',
        'paper_markouts',
        'paper_order_owners',
        'paper_order_reservations',
        'paper_orders',
        'paper_owner_positions',
        'paper_positions',
        'polymarket_book_deltas',
        'polymarket_book_snapshots',
        'polymarket_book_snapshots_full',
        'polymarket_data_gaps',
        'polymarket_event_markets',
        'polymarket_events',
        'polymarket_macro_calendar',
        'polymarket_macro_releases',
        'polymarket_market_metadata_versions',
        'polymarket_markets',
        'polymarket_oi_holders',
        'polymarket_param_versions',
        'polymarket_resolution_events',
        'polymarket_resolution_input_changes',
        'polymarket_retention_log',
        'polymarket_rtds_1m',
        'polymarket_rtds_prices',
        'polymarket_rule_versions',
        'polymarket_series_1m',
        'polymarket_trades',
        'polymarket_universe_log',
        'portfolio_circuit_breakers',
        'portfolio_config_versions',
        'portfolio_cycle_summary',
        'portfolio_decision_hourly',
        'portfolio_decisions',
        'portfolio_exposures',
        'portfolio_factor_map_versions',
        'portfolio_g2_clock',
        'portfolio_g2_clock_events',
        'portfolio_gate_measurements',
        'portfolio_gate_reports',
        'portfolio_panel_snapshots',
        'portfolio_position_entries',
        'portfolio_state',
        'portfolio_state_events',
        'resolution_adjudication_samples',
        'resolution_clarifications',
        'resolution_layer_divergences',
        'resolution_market_state',
        'resolution_onchain_cursor',
        'resolution_onchain_events',
        'resolution_reports',
        'resolution_runtime_state',
        'resolution_score_versions',
        'resolution_scores',
        'resolution_uma_timeline',
        'strategy_decisions'
    ]::text[])) THEN
        RAISE EXCEPTION 'RETIREMENT_PIN_REQUIRES_CLASSIFICATION';
    END IF;
END $$;

DROP VIEW paper_attributed_ledger_v1 RESTRICT;

DROP TABLE
    fast_config_versions,
    fast_wallet_state,
    fundamental_calibration_reports,
    fundamental_estimates,
    fundamental_gate_reports,
    fundamental_labels,
    fundamental_model_events,
    fundamental_models,
    graph_edges,
    graph_sanity_vetoes,
    graph_violations,
    paper_feature_windows,
    paper_fill_reports,
    paper_fill_samples,
    paper_financial_owners,
    paper_kill_switch,
    paper_ledger_events,
    paper_ledger_owners,
    paper_markouts,
    paper_order_owners,
    paper_order_reservations,
    paper_orders,
    paper_owner_positions,
    paper_positions,
    polymarket_book_deltas,
    polymarket_book_snapshots,
    polymarket_book_snapshots_full,
    polymarket_data_gaps,
    polymarket_event_markets,
    polymarket_events,
    polymarket_macro_calendar,
    polymarket_macro_releases,
    polymarket_market_metadata_versions,
    polymarket_markets,
    polymarket_oi_holders,
    polymarket_param_versions,
    polymarket_resolution_events,
    polymarket_resolution_input_changes,
    polymarket_retention_log,
    polymarket_rtds_1m,
    polymarket_rtds_prices,
    polymarket_rule_versions,
    polymarket_series_1m,
    polymarket_trades,
    polymarket_universe_log,
    portfolio_circuit_breakers,
    portfolio_config_versions,
    portfolio_cycle_summary,
    portfolio_decision_hourly,
    portfolio_decisions,
    portfolio_exposures,
    portfolio_factor_map_versions,
    portfolio_g2_clock,
    portfolio_g2_clock_events,
    portfolio_gate_measurements,
    portfolio_gate_reports,
    portfolio_panel_snapshots,
    portfolio_position_entries,
    portfolio_state,
    portfolio_state_events,
    resolution_adjudication_samples,
    resolution_clarifications,
    resolution_layer_divergences,
    resolution_market_state,
    resolution_onchain_cursor,
    resolution_onchain_events,
    resolution_reports,
    resolution_runtime_state,
    resolution_score_versions,
    resolution_scores,
    resolution_uma_timeline,
    strategy_decisions
RESTRICT;

DROP FUNCTION
    capture_polymarket_market_metadata_version(),
    capture_resolution_event_membership_change(),
    capture_resolution_input_change(),
    fast_config_versions_guard(),
    fundamental_models_guard(),
    normalize_polymarket_market_affirmative_token(),
    paper_financial_decimal9(value jsonb),
    paper_late_owner_validate(),
    paper_ledger_assign_owners(),
    paper_ledger_events_guard(),
    paper_ledger_owner_validate(),
    paper_ledger_retry_guard(),
    paper_open_owner_tokens(before_event_ts timestamp with time zone, before_idempotency_key text, exclude_event_id bigint, for_token_id text),
    paper_order_assign_owner(),
    paper_order_financial_identity_guard(),
    paper_ownership_append_only(),
    paper_reconcile_reservations(owner_account text, owner_strategy text),
    paper_reservation_assert_balances(owner_account text, owner_strategy text),
    paper_reservation_event_guard(),
    paper_reservation_event_project(),
    paper_reservation_identity_guard(),
    polymarket_event_markets_append_only_guard(),
    polymarket_market_metadata_versions_guard(),
    polymarket_universe_log_append_only_guard(),
    portfolio_config_versions_guard(),
    portfolio_decisions_guard(),
    portfolio_gate_measurements_guard(),
    portfolio_position_entries_guard(),
    portfolio_state_events_guard(),
    resolution_clarifications_guard(),
    resolution_input_changes_guard(),
    resolution_onchain_events_guard(),
    resolution_score_versions_guard(),
    resolution_scores_guard(),
    resolution_uma_timeline_guard(),
    strategy_decisions_guard()
RESTRICT;

-- The old generic foundation HOLD remains enforced on its surviving relations.
-- BTC uses its independent btc_retention_* policy, pins, guards and ledger.
CREATE OR REPLACE FUNCTION retention_evidence_tables() RETURNS text[]
LANGUAGE sql IMMUTABLE PARALLEL SAFE
AS $$ SELECT ARRAY[
    'app_settings',
    'audit_events',
    'bonding_curve_state',
    'domain_events',
    'event_quarantine',
    'pumpswap_pool_state'
]::text[] $$;

INSERT INTO schema_versions(component,version,checksum_sha256)
VALUES ('foundation', :'migration_version'::integer, :'migration_checksum')
ON CONFLICT(component,version) DO NOTHING;
